chore: use rsetup instead of manual configs
radxa-pkg/radxa-oobe pull request #2
Opened 2024-07-18 07:40 UTC by RadxaPanda

2024-07-18 07:51 UTC, RadxaPanda commented
@RadxaYuntian pls check this out

2024-07-18 07:53 UTC, RadxaYuntian commented
You can request reviewer on the right side. There should also be a CODEOWNERS file to automate this step.

2024-07-18 07:54 UTC, RadxaYuntian requested changes

2024-07-18 07:54 UTC, RadxaYuntian commented on debian/postinst
> +    rsetup set_autologin_status serial-getty@.service on
```suggestion
    rsetup set_autologin_status serial-getty@.service oem on
```

2024-07-18 07:54 UTC, RadxaYuntian commented on debian/postrm
> +        rsetup set_autologin_status serial-getty@.service off
```suggestion
        rsetup set_autologin_status serial-getty@.service oem off
```

2024-07-18 07:55 UTC, RadxaYuntian requested changes

2024-07-18 07:55 UTC, RadxaYuntian commented on debian/control
> +         systemd,
```suggestion
```
If we ever support multiple init systems, it should be `rsetup` to handle the difference between them.

2024-07-19 02:34 UTC, RadxaYuntian requested changes
squash

2024-07-19 10:20 UTC, RadxaYuntian approved these changes

2024-07-19 10:20 UTC, merged